name: CI

on:
  push:
  pull_request:
  schedule:
    # Weekly Wednesday 6 AM build
    # * is a special character in YAML so you have to quote this string
    - cron: '0 6 * * 3'

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Fetch tags
      run: git fetch --prune --unshallow --tags
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # No numpy/scipy wheel for 3.9 yet
    - name: Install and build
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install astropy==4.2rc1
        python -m pip install -e .[test]
    - name: Test
      run: pytest
